package com.intuit.craftdemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="BusinessProfile")
public class BusinessProfile {
		
	@DynamoDBHashKey(attributeName = "companyName")
	private String companyName;
	
	@DynamoDBAttribute(attributeName = "legalName")
	private String legalName;
	
	@DynamoDBAttribute(attributeName = "businessAddress")
	private String businessAddress;
	
	@DynamoDBAttribute(attributeName = "legalAddress")
	private String legalAddress;
	
	@DynamoDBAttribute(attributeName = "taxIdentifier")
	private String taxIdentifier;
	
	@DynamoDBAttribute(attributeName = "email")
	private String email;
	
	@DynamoDBAttribute(attributeName = "website")
	private String website;
	
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	
	public void setLegalName(String legalName) {
		this.legalName = legalName;
	}
	
	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress;
	}

}
