package com.intuit.craftdemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="BusinessProfile")
public class BusinessProfile {
	
	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName = "companyName")
	private String companyName;
	
	@DynamoDBAttribute(attributeName = "legalName")
	private String legalName;
	
	@DynamoDBAttribute
	private String businessAddress;
	
	@DynamoDBAttribute
	private String legalAddress;
	
	@DynamoDBAttribute
	private String taxIdentifier;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private String website;

	public void setId(String id) {
		this.id = id;		
	}
	
	public String getId() {
		return this.id;
	}
}
