package com.intuit.craftdemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="BusinessProfile")
public class BusinessProfile {
		
	@DynamoDBHashKey(attributeName = "companyName")
	private String companyName;
	
	@DynamoDBAttribute
	private String legalName;
	
	@DynamoDBAttribute
	private String businessAddress;
	
	@DynamoDBAttribute
	private String legalAddress;
	
	@DynamoDBAttribute
	private String taxIdentifier;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private String website;
	
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	
	public String getCompanyName() {
		return this.companyName;
	}
	
	public void setLegalName(String legalName) {
		this.legalName = legalName;
	}
	
	public String getLegalName() {
		return this.legalName;
	}
	
	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress;
	}
	
	public String getBusinessAddress() {
		return this.businessAddress;
	}
	
	public void setLegalAddress(String legalAddress) {
		this.legalAddress = legalAddress;
	}
	
	public String getLegalAddress() {
		return this.legalAddress;
	}
	
	public void setTaxIdentifier(String taxIdentifier) {
		this.taxIdentifier = taxIdentifier;
	}
	
	public String getTaxIdentifier() {
		return this.taxIdentifier;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getEmail() {
		return this.email;
	}
	
	public void setWebsite(String website) {
		this.website = website;
	}
	
	public String getWebsite() {
		return this.website;
	}

}
